### ISSUE TITLE
Uncaught Error: kill ESRCH

### ISSUE THREAD

**Issue by keyscores** [pkrumins/node-tree-kill#16]
On node 4.6 I'm getting:  Uncaught Error: kill ESRCH . This means the pid does not exist.
However I am checking to see if the process exists before killing it:

               if( process.kill( pid, 0) ){ //checks if the pid exists
                 kill( pid )
               }

This only happens when I'm starting and killing processes back to back in a test runner.

Any clues on what might cause this?

**Comment by wmhilton** [comment]
What operating system are you on? I think sending signals other than SIGTERM is OS dependent. (Definitely doesn't work on Windows...)

**Comment by keyscores** [comment]
I think we can close this, in the mean time I discovered that my test runner was doing some unexpected async calls. 
One thing could be clarified in the docs. Do the callback run every time or only on error?

**Comment by wmhilton** [comment]
Run every time. Only pass an argument if there's an error.
